kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      # Map host port 80 to the container's port 80 for HTTP
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      # Map host port 443 to the container's port 443 for HTTPS
      - containerPort: 443
        hostPort: 443
        protocol: TCP
